### ISSUE TITLE
could not find function "points_in_circle"

### ISSUE THREAD

**Issue by mungacharl** [MHaringa/spatialrisk#1]
After installing the library and running the first example, I am getting the above stated error

**Comment by MHaringa** [comment]
Hi, I am not able to reproduce your error.. What if you try the following?

```
spatialrisk::points_in_circle(spatialrisk::Groningen, lon_center = 6.571, lat_center = 53.213)
```

**Comment by mungacharl** [comment]
Found out I was using a lower version of R (3.2.0). Its working in version 4.0.5 currently
